import java.util.ArrayList;


/**
 * <h1>Truck</h1> Represents a Truck
 */
public class Truck extends Vehicle {
    private String licensePlate;
    private double maxWeight;
    private double currentWeight;
    private int zipDest;
    private ArrayList<Package> packages;
    private final double GAS_RATE = 1.66;

    /**
     * Default Constructor
     */
    //============================================================================

    public Truck() {
    }
    //============================================================================

    /**
     * Constructor
     *
     * @param licensePlate license plate of vehicle
     * @param maxWeight    maximum weight that the vehicle can hold
     */
    //============================================================================

    public Truck(String licensePlate, double maxWeight) {
        super (licensePlate, maxWeight);
    }

    //============================================================================

    /*
     * =============================================================================
     * | Methods from Profitable Interface
     * =============================================================================
     */

    /**
     * Returns the profits generated by the packages currently in the Vehicle.
     * <p>
     * &sum;p<sub>price</sub> - (range<sub>max</sub> &times; 1.66)
     * </p>
     */
    @Override
    public double getProfit() {
        double revenue = 0;
        int maxRange = 0;
        for (Package p:
             this.packages) {
            revenue += p.getPrice();
            if (Math.abs(p.getDestination().getZipCode()) > maxRange)
                maxRange = Math.abs(p.getDestination().getZipCode());
        }
        return revenue - maxRange * GAS_RATE;

    }

    /**
     * Generates a String of the truck report. Truck report includes:
     * <ul>
     * <li>License Plate No.</li>
     * <li>Destination</li>
     * <li>Current Weight/Maximum Weight</li>
     * <li>Net Profit</li>
     * <li>Shipping labels of all packages in truck</li>
     * </ul>
     *
     * @return Truck Report
     */
    @Override
    public String report() {
        //TODO: Print Shipping Labels
        String output = "==========Truck Report==========\n" +
                "License Plate No.: " + licensePlate + "\n" +
                "Destination: " + zipDest + "\n" +
                "Weight Load: " + String.format("%.2f",currentWeight) + "/" + String. format("%.2f", maxWeight) + "\n" +
                "Net Profit: $" + String.format("%.2f", this.getProfit()) + "\n=====Shipping Labels=====";
        for (int i = 0; i < packages.size(); i++)
        {
            output += (packages.get(i).shippingLabel() + "\n");
        }
        output += "\n==============================";

        return output;

    }


}